### PR TITLE
ci: test that the package lint and pre-commit versions first

### PR DESCRIPTION
**Pull request by afuetterer**
## Description

Related issue: #938

- [x] remove commit `test if test run fails early` (only for demonstration purposes)

## Types of Changes
- [x] Other (please describe): Maintenance, CI

## Checklist
- [x] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/main/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by afuetterer** [comment]
Can you have a look at the failed test run @MyPyDavid?
https://github.com/rdmorganiser/rdmo/actions/runs/8250046705

There is an annotation under `Test (Python: 3.12, DB: postgres): rdmo/core/tests/test_package_status.py#L48`.

Is this what you wanted?

**Comment by MyPyDavid** [comment]
yes exactly! nice 😄  🙏

**Review by MyPyDavid — CHANGES_REQUESTED** [review]
Thanks!
some magic is in the https://github.com/pytest-dev/pytest-github-actions-annotate-failures

request changes for removing the extra commit ;)

**Review by MyPyDavid — APPROVED** [review]
thanks!

**Pull request merged**
