### PR TITLE
[preparation for] Release 2.3.0

### PR DESCRIPTION
**Pull request by MyPyDavid**
## Description

Release branch for new features planned for RDMO 2.3.0

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/main/CONTRIBUTING.md).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jochenklar** [comment]
Can we rename this branch just to `2.3.0`? I am doing `git checkout dev-2.2.0` very often and every char is expensive!

**Comment by MyPyDavid** [comment]
you don't have something like this? https://github.com/jimhester/per-directory-history
autofill for your commands..
otherwise I would prefer `r-2.3.0` for example..

**Comment by jochenklar** [comment]
I think there will be no confusion since we delete `2.3.0` when we merge to main and then we have the tag.

**Comment by MyPyDavid** [comment]
this can be closed and a new pr with `2.3.0` can be opened....

**Comment by jochenklar** [comment]
Yes, lets do that after the release.

**Comment by jochenklar** [comment]
@MyPyDavid @afuetterer I have no clue why this PR says I merged it into `main` (which I didn't) do you guys have any idea? I will delete the branch (in favor of `2.3.0`), but I want to check if there is a problem first.

**Comment by afuetterer** [comment]
Maybe the head commit came from another branch and github ui is confused? No idea. I guess this should be safe to delete.

**Comment by jochenklar** [comment]
Jupp, makes sense.

**Pull request merged**
