### PR TITLE
Add parent attributes to full export

### PR DESCRIPTION
**Pull request by jochenklar**
This PR adds all parent attributes to the full export feature.

### CODE REVIEW

**Comment by MyPyDavid** [comment]
do you not want to have any tests for this?
For example in here: https://github.com/rdmorganiser/rdmo/blob/dd3cb84d6d40f2a8ec720884b3c2eb69eec10dea/rdmo/questions/tests/test_viewset_catalog.py#L241 ?

**Comment by jochenklar** [comment]
I mean, there is a test, right? We could test that everything is there though.

**Comment by MyPyDavid** [comment]
yes a general test is there, I mean testing for the specific content of the exported xml (which attributes should be in there..)

**Comment by jochenklar** [comment]
I added some tests.

**Review by MyPyDavid — APPROVED** [review]
thanks!

**Pull request merged**
