### PR TITLE
Refactor progress bar and overview

### PR DESCRIPTION
**Pull request by jochenklar**
This PR aims to:
- [x] Fix the progress bar (#596)
- [x] Stores the progress in the projects model and updates on saving values (#488)
- [x] Shows which pages are fully answered in the overview (#299, #424)

### CODE REVIEW

**Comment by jochenklar** [comment]
Input from @sa-wetter: Numbers should be always show in the progress bar.

**Review by MyPyDavid — CHANGES_REQUESTED** [review]
think it works nicely in the interview!
It has a lot of logic in the `progress.py`  and looks well-tested.
Is the recursivity really necessary? It will be hard to debug or change, but it works now so...
Ive added a small refactor for the `ValueQuerySet` manager, maybe this can be used in other places as well..

In the project overview, I would rather have the progess as `15/30` instead of `50%` but this can be easily changed.

**Comment by MyPyDavid** [comment]
Had one more question, it does not update the progress with the Question Autosave or?

**Comment by jochenklar** [comment]
It does work! Just tested. Can I merge?

**Review by MyPyDavid — APPROVED** [review]
thanks!

**Comment by jochenklar** [comment]
I changed the view in the projects table to match the string in the interview.

**Pull request merged**
