### PR TITLE
build: batch update javascript dependencies

### PR DESCRIPTION
**Pull request by afuetterer**
## Description

This PR proposes the following changes:

- update the Javascript dependencies in multiple grouped commits
- alter the dependabot config slightly (move `copy-webpack-plugin` to the more fitting `webpack` update group
- update the used versions of eslint and react plugin in pre-commit config

## Types of Changes
- [x] Build related changes

## Checklist
- [x] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/master/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by afuetterer** [comment]
These are all the updates the Dependabot made to my fork today, so JS dependencies should be up to date. The grouping works fine. We can always reduce the number of the groups later. But this a step forward from having dozens of PRs dangling around.

The frontend tests passed in my fork. Maybe you could look at the management frontend manually with the wheel from this PR @MyPyDavid?

**Comment by MyPyDavid** [comment]
yes, good idea but now there is no artifact in the PR.

Artifacts 
– 

Maybe the [rdmorganiser:dependency-updates](https://github.com/rdmorganiser/rdmo/tree/dependency-updates) still needs be updated with a rebase or?

**Comment by afuetterer** [comment]
You are right, the build-wheel is not available in dependency-updates.

**Comment by MyPyDavid** [comment]
alright, branch is updated and it's running again, i'll check afterwards for the artifact

**Comment by afuetterer** [comment]
Now I need to rebase my branch as well. There are some commits in this PR, that are already on the dependency-updates branch. I will fix this later.

**Comment by afuetterer** [comment]
See #839

**Pull request closed without merging**
