### PR TITLE
Show all catalogs

### PR DESCRIPTION
**Pull request by CalamityC**
## Description

Related issue: #ISSUE_NUMBER

### CODE REVIEW

**Review by jochenklar — CHANGES_REQUESTED** [review]
Thanks! One tiny thing, if the non-available catalog is selected it is barely readable (dark-gray on blue). Can you add a css rule to make text-muted white when active?

**Review by jochenklar — APPROVED** [review]
Awesome, thanks!

**Comment by jochenklar** [comment]
@CalamityC can we merge this?

**Comment by CalamityC** [comment]
> @CalamityC can we merge this?

Can we wait until I showed the outcome to Jürgen? I probably speak to him tomorrow

**Pull request merged**
