### PR TITLE
Nested projects

### PR DESCRIPTION
**Pull request by jochenklar**
- [x] Introduce nested projects
- [ ] Inherit memberships from parent projects
- [ ] Use child projects in templates

### CODE REVIEW

**Comment by jochenklar** [comment]
We will use the new `dev` branch.

**Comment by MyPyDavid** [comment]
I was looking into something like "Inherit memberships from parent projects"

In your comment @jochenklar, this checkbox is still open.
> * [x]  Introduce nested projects
> 
> * [ ]  Inherit memberships from parent projects
> 
> * [ ]  Use child projects in templates

However, in our test it looks like this is already implemented, is this the case?

**Comment by jochenklar** [comment]
Hi, yes this is an oversight, did not finish all the paperwork...

**Comment by jochenklar** [comment]
Child projects in views are documented here: https://rdmo.readthedocs.io/en/latest/management/views.html#child-projects.

**Comment by MyPyDavid** [comment]
thanks!

**Pull request closed without merging**
