### PR TITLE
docs: add meta-comment about comment in pr template

### PR DESCRIPTION
**Pull request by afuetterer**
## Description

I saw this "meta-comment" in another repository recently and I thought I would add it here. So let contributors know, that they do not have to remove all the comments before creating PRs.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/master/CONTRIBUTING.md).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MyPyDavid** [comment]
yes, this can be helpful

**Review by jochenklar — APPROVED** [review]

**Review by MyPyDavid — APPROVED** [review]

**Comment by afuetterer** [comment]
Can I merge, if I have two approvals?

**Comment by jochenklar** [comment]
Yes, go for it! I would say the general policy is that the person who cretes the PR merges, after approval.

**Comment by afuetterer** [comment]
Alright, thank you. That sounds reasonable.
Maybe we document that policy somewhere?

**Pull request merged**
