### PR TITLE
ci: switch from PyUp to Dependabot

### PR DESCRIPTION
**Pull request by afuetterer**
Hi there,

this is my first PR to the project. Should PRs be pointed to master? Feel free to change or close.

Refs: #645

### CODE REVIEW

**Comment by jochenklar** [comment]
Hi @afuetterer , thanks a lot! We usually have a `dev-*` branch for each release. Right now, it is a bit more complicated since we are working in `1.11.0` and `2.0.0` simultaneously. I will adjust the PR. btw: we have a developer meeting every month, if you are interested, and a slack. You can just send me a mail and I will invite you.

**Comment by afuetterer** [comment]
Thank you @jochenklar. So PRs should point to a `dev-*` branch, but now there are two of those. :smile: 

I know about the developer meetings. I will try to attend one of the next ones.

**Comment by jochenklar** [comment]
Ah, sorry, yes, I forgot that this should be in master now. Please create a new PR to master. I cannot reopen here.

**Comment by afuetterer** [comment]
No problem, GitHub magic at work. I will open another PR to master then.

**Pull request closed without merging**
