### PR TITLE
Add SITE_ID, DEBUG_TOOLBAR, ALLOWED_HOSTS, and BASE_URL to settings

### PR DESCRIPTION
**Pull request by jochenklar**

### CODE REVIEW

**Comment by MyPyDavid** [comment]
Do you want to split the settings in here? Or is the dependency in here for the `rdmo-app`?

**Comment by jochenklar** [comment]
The nice thing about django-slit-settings is that you dont need to include `AUTHENTICATION_BACKENDS`, `MIDDLEWARES`, etc. in `local.py` anymore.

**Comment by jochenklar** [comment]
@MyPyDavid can I merge?

**Review by MyPyDavid — APPROVED** [review]
yes, looks good, thanks! 
Think that default value for `BASE_URL` will also prevent some issues in deployments.

**Comment by afuetterer** [comment]
I can fix the merge conflict, if you want.

**Comment by afuetterer** [comment]
Damn it, I tried the GitHub web UI to resolve the merge conflict. I did not realize that it would then merge the branch. A rebase would have sufficed.
Should I force push later and fix this?

**Comment by MyPyDavid** [comment]
Do you mean to force the branch back to b4d0452e3d16e59535451aa9eb2f844b85b7aa73 and then rebase?

**Comment by jochenklar** [comment]
yes, I would checkout the old commit, rebase, force push.

**Comment by afuetterer** [comment]
Done, sorry for the confusion.

**Comment by jochenklar** [comment]
Urgs, now it does not work with the old `rdmo-app` anymore ... I think we need to remove `BASE_URL` again, and set it in the new `rdmo-app`.

**Comment by jochenklar** [comment]
Alternatively we can set it to `BASE_URL = ''`. What do you think @MyPyDavid ?

**Pull request merged**
