### PR TITLE
Interview section progress

### PR DESCRIPTION
**Pull request by jochenklar**
This PR adds the progress for section to the navigation in the interview. As with the validators, we could also release this in RDMO 2.2.0 since the changes in the old frond end are small.

### CODE REVIEW

**Comment by MyPyDavid** [comment]
this remains for 2.3?

**Comment by MyPyDavid** [comment]
it needs to be rebased to dev-2.2.0 first please.. it was based to `interview`

**Comment by jochenklar** [comment]
There is now https://github.com/rdmorganiser/rdmo/pull/1041 for the `dev-2.2.0` release.

**Comment by jochenklar** [comment]
The interview part was merged locally. Closing here.

**Pull request closed without merging**
