### PR TITLE
 Short title for Section and Page

### PR DESCRIPTION
**Pull request by jochenklar**
This PR adds a new field `short_title` to `Section` and `Page`. If set, this field populates the navigation instead of the `title` which might be to long. See also https://github.com/rdmorganiser/rdmo/issues/363 and https://github.com/rdmorganiser/rdmo/issues/346.

### CODE REVIEW

**Review by MyPyDavid — CHANGES_REQUESTED** [review]
tests are missing, even though it's mainly Django and DRF stuff

**Comment by MyPyDavid** [comment]
I think I would need to add this to the import (https://github.com/rdmorganiser/rdmo/pull/810) afterwards as well

**Comment by jochenklar** [comment]
No sorry I don't think we need tests here. The only thing which could be tested is that short_title is used and not title if it is set. I don't want to mess with the fixtures just for that.

**Comment by jochenklar** [comment]
Ah crap and to the export!

**Comment by MyPyDavid** [comment]
yes, I think to have a model field represented in a test fixture should be a minimum or not??

**Comment by jochenklar** [comment]
I don't think we need that every time. We need to update the fixtures and the xml files at one point in the future, but not now.

**Comment by jochenklar** [comment]
Force push after interactive rebase.

**Review by MyPyDavid — APPROVED** [review]
thanks!

**Pull request merged**
