### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by jochenklar**
This PR changes/fixes 2 minor things mentioned in #254:

* Fix string translation (Projektaufgaben, Projektansichten)
* Add `accept=".xml"` to upload forms to restrict the selection in the browser dialog to XML files. For project imports this information is automatically taken from the plugin classes.
* add `email` to `RoleAdmin`

### CODE REVIEW

**Comment by MyPyDavid** [comment]
do you want to merge these in [2.0.2](https://github.com/rdmorganiser/rdmo/pull/799)?

**Comment by jochenklar** [comment]
No let's wait for 2.1.0.

**Comment by jochenklar** [comment]
Can I merge?

**Comment by MyPyDavid** [comment]
I've added `email` to RoleAdmin, is ok?

**Review by MyPyDavid — APPROVED** [review]

**Pull request merged**
