### PR TITLE
chore: add official support for python 3.12

### PR DESCRIPTION
**Pull request by afuetterer**
## Description

Related issue: #704

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist
- [x] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/master/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jochenklar — APPROVED** [review]

**Comment by MyPyDavid** [comment]
so when all the tests pass, it means that all the dependencies are compatible with 3.12 as well? and we don't need to test for 3.11 anymore?

**Comment by afuetterer** [comment]
We can still test for 3.11 of course, I just followed your approach of testing the min and max versions of Python.

All tests are passing, so they are a) installable with Python 3.12, also optional dependencies and b) rdmo still works as expected.

**Comment by afuetterer** [comment]
We can use `python-version: ['3.8', '3.11', '3.12']`, if you prefer.

**Review by MyPyDavid — APPROVED** [review]

**Comment by jochenklar** [comment]
We tested for all versions before, but I think testing the min/max versions should be ok. I would guess that things break if we use to new features in an old version, or if features we use are changed in a new version. Both cases should be covered with only the minimum maximum version.

**Comment by afuetterer** [comment]
I did not choose this approach, it was already in place.
See e.g. https://github.com/rdmorganiser/rdmo/commit/322d0a698ad344f09ad6d50a011244b37884c2ca

Yes, I think that is correct. If we use bleeding edge Python 3.12 features, the tests for 3.8 will fail. In my opinion that is enough of a safety net. But sure, lots of projects test with 3.8, 3.9, 3.10,  3.11, 3.12. And then also for Windows, Mac and Linux. That is overkill for a project like rdmo in my opinion. But a library like requests, that is used all over the place should have such testing.

What do you think? Go for the merge then?

**Pull request merged**
