### PR TITLE
RDMO 2.0.1

### PR DESCRIPTION
**Pull request by jochenklar**
Here we go again ...

### CODE REVIEW

**Comment by MyPyDavid** [comment]
when I open edit catalog for the first time these is a js warning:

> Warning: Received `false` for a non-boolean attribute `title`.
> 
> If you want to write it to the DOM, pass a string instead: title="false" or title={value.toString()}.
> 
> If you used to conditionally omit it with title={condition && value}, pass title={condition ? value : undefined} instead.
> button
> div
> OrderedMultiSelect@webpack://rdmo/./rdmo/management/assets/js/components/edit/common/OrderedMultiSelect.js?:220:20
> div
> div
> EditCatalog@webpack://rdmo/./rdmo/management/assets/js/components/edit/EditCatalog.js?:57:16
> Edit@webpack://rdmo/./rdmo/management/assets/js/components/main/Edit.js?:37:16
> Main@webpack://rdmo/./rdmo/management/assets/js/containers/Main.js?:42:16
> ConnectFunction@webpack://rdmo/./node_modules/react-redux/es/components/connectAdvanced.js?:234:68
> Provider@webpack://rdmo/./node_modules/react-redux/es/components/Provider.js?:19:15
> DndProvider@webpack://rdmo/./node_modules/react-dnd/dist/core/DndProvider.js?:43:25
> 

Maybe a bug in?
https://github.com/rdmorganiser/rdmo/blob/ea0a73b1344670c708600916e7c04c41a5b20e62/rdmo/management/assets/js/components/edit/EditCatalog.js#L22

**Comment by MyPyDavid** [comment]
for dev docs on tests, pytest needs a `mkdir testing/log` ?

**Comment by afuetterer** [comment]
As this is "only" a patch version update, how many more commits do you collect here?

Maybe release 2.0.1 now, because the main reason for it was the bugfix?

We can continue with 2.0.2 or 2.1 then?

**Comment by jochenklar** [comment]
Yes, this should just fix problems with `2.0.0` and should be released early next week.

**Comment by jochenklar** [comment]
Maintainance stuff is ok though.

**Review by MyPyDavid — APPROVED** [review]
have checked it out locally, works and bug is fixed

**Pull request merged**
