### PR TITLE
add show/hide URI buttons in questions/catalogs management

### PR DESCRIPTION
**Pull request by MyPyDavid**
I've added checkboxes in the header of the questions/catalogs management page which can show/hide the URI for each element on the page.

Implementation for: https://github.com/rdmorganiser/rdmo/issues/449

### CODE REVIEW

**Comment by jochenklar** [comment]
Hey @MyPyDavid, I thing the checkboxes should go to the sidebar (like `Show questions`). But then there ist little space. Maybe we need some kind of accordeon which can be opened to reveal all checkboxes.

**Comment by MyPyDavid** [comment]
I've moved these checkboxes now to the sidebar and gave them corresponding `<code>` colors.

We don't need the checkbox for `catalogs`, `sections` and `question sets`, so now there are only 4 left (see picture).
This fits also without accordion or?

I've added the `margin-bottom : 0` via an `ng-style` conditional statement.


showURI-checkboxes

**Comment by jochenklar** [comment]
All fine, but the spacing seems a bit uneven. Can you try:

```
.showURI-checkbox {
    margin-top: 0 !important;
    margin-bottom: 15px !important;
}
```

and

```
<ul class="list-showURI-checkboxes" ng-show="service.showURIs">
  <li class="form-group showURI-checkbox checkbox" ng-show="service.showQuestionSets && service.showQuestions">
    <label>
      <input type="checkbox" ng-model="service.showURIQuestions">
      <code class="code-questions" title="{% trans 'URI' %}">{% trans 'Questions' %}</code>
    </label>
  </li>
  <li class="form-group showURI-checkbox checkbox" ng-show="service.showQuestionSets">
    <label>
      <input type="checkbox" ng-model="service.showURIConditions">
      <code class="code-conditions" title="{% trans 'Condition' %}">{% trans 'Conditions' %}</code>
    </label>
  </li>
  <li class="form-group showURI-checkbox checkbox" ng-show="service.showQuestionSets">
    <label>
      <input type="checkbox" ng-model="service.showURIAttributes">
      <code title="{% trans 'Attributes' %}">{% trans 'Attributes' %}</code>
    </label>
  </li>
  <li class="form-group showURI-checkbox checkbox" ng-show="service.showQuestionSets && service.showQuestions">
    <label>
      <input type="checkbox" ng-model="service.showURIOptions">
      <code class="code-options" title="{% trans 'Options' %}">{% trans 'Options' %}</code>
    </label>
  </li>
</ul>
```

This cleans up the markup a bit and uses the `.checkbox` class we use in RDMO elsewhere.

**Comment by MyPyDavid** [comment]
The checkboxes are now evenly spaced but there is still an extra empty space between the bottom of the checkboxes and the next "Options" header.
I think it comes from the `input-group`, do you know where I can style that to `0` @jochenklar ?

uri-checkboxes-aligned-2

**Comment by jochenklar** [comment]
Fixed here: https://github.com/rdmorganiser/rdmo/commit/5b03abcfb82af6637691aeb24e96cbb01bb2c805

**Comment by MyPyDavid** [comment]
thanks, looks nice and evenly spaced now!

**Pull request merged**
