### PR TITLE
docs: add additional badges to readme

### PR DESCRIPTION
**Pull request by afuetterer**
## Description

This PR proposes a few more badges for the readme. This shows clearly at first glance, that the project uses pre-commit and ruff. Also there is an indicator of the number of downloads from pypi. What do you think?

The order is not fixed. We can rearrange of course.

## Types of Changes
- [x] Documentation content changes

## Checklist

- [x] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/master/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by jochenklar** [comment]
Hmm, I like the ruff one, but I don't like the downloads (I think those kind of stats are misleading). It also looks a bit much. Can you remove the empty lines so that the badges are in one line and wrapping automatically (I hope).

**Comment by afuetterer** [comment]
I moved pre-commit and ruff inwards, because those will not change any time soon. But CI, Coverage and Docs status badges might change with each commit. So I put those at the end of the line.

What do you think?

**Comment by jochenklar** [comment]
Maybe we should use something like `3.8 - 3.12` instead of listing all versions. If we save some space the shields would not need to wrap anymore. Also I think the `docs` badge is weird since it concerns a different repo.

**Comment by afuetterer** [comment]
Alright, remove the "docs: passing" badge then and only show docs status in docs repo. The badge was already there, I did not add it.

Sure we can hardcode 3.8 - 3.12. I added a dynamic badge recently, so that we never forget to update here. But yes 3.8,9,10,11,12 is quite a long badge.

Will adapt soon.

**Comment by afuetterer** [comment]
Add markdown line break after license.

**Comment by jochenklar** [comment]
Thanks! We need another badge for the first row, then it would look better. Maybe we find something.

**Comment by afuetterer** [comment]
> Thanks! We need another badge for the first row, then it would look better. Maybe we find something.

Maybe a badge about the Django version?

**Comment by afuetterer** [comment]
Something like: [django-versions](https://pypi.python.org/pypi/rdmo/)

This badge is usually used for a library, that supports multiple django versions, e.g. 3,4,5... This could show at a quick glance, that django is at 4.2.

**Comment by jochenklar** [comment]
Its maybe also cool to show that it is django based.

**Comment by afuetterer** [comment]
I came across this one recently: [Maintenance](https://github.com/rdmorganiser/rdmo/graphs/commit-activity)

It shows if there is recent activity.

**Comment by jochenklar** [comment]
ne, die finde ich alle ästhetisch schwierig, ich glaube das mit der django version reicht.

**Comment by afuetterer** [comment]
Ready.

**Review by jochenklar — APPROVED** [review]

**Comment by MyPyDavid** [comment]
these [admin.register decorators](https://github.com/rdmorganiser/rdmo/pull/778/commits/0e664caee16c112674b5760b6fffc137550d72d5) are also in this PR?

**Comment by afuetterer** [comment]
> these [admin.register decorators](https://github.com/rdmorganiser/rdmo/pull/778/commits/0e664caee16c112674b5760b6fffc137550d72d5) are also in this PR?

Sorry, no, I need to rebase. That happened because I switched the base branch of thir PR from 2.10 to 2.02. 2.10 contains the admin-register commit. I will fix this.

**Comment by afuetterer** [comment]
Fixed.

**Comment by afuetterer** [comment]
Can I merge @MyPyDavid?

**Review by MyPyDavid — APPROVED** [review]
yes, thanks!

**Pull request merged**
