### PR TITLE
Dev 2.2.0 section progress

### PR DESCRIPTION
**Pull request by jochenklar**
This PR is the 2.2.0 version of https://github.com/rdmorganiser/rdmo/pull/1028.

### CODE REVIEW

**Comment by MyPyDavid** [comment]
Locally, in an existing project, the progress status numbers in the sections popped up only after creating my first dataset. 
Could this be a bug?

**Comment by jochenklar** [comment]
I think this is how I implemented it. Do you think the `(0/10)` should be there all the time?

**Comment by MyPyDavid** [comment]
Ah no, now I've tried in new project and then they pop up gradually during the interview. 
No, like this is fine, think `(0/10)` everywhere would be too much information.

**Review by MyPyDavid — APPROVED** [review]
thank you!

**Pull request merged**
