### PR TITLE
build(opt-deps): dependency updates 2.0.1 (actions/checkout v4 and allauth 0.57)

### PR DESCRIPTION
**Pull request by MyPyDavid**
Maybe we can collect multiple dependency updates in here.

## Description

* update django-allauth requirement to 0.57.0
* [build(deps): bump actions/checkout from 3 to 4](https://github.com/rdmorganiser/rdmo/pull/740/commits/61777fba3e9658b8e3a336ad369bb6449168d424)

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/master/CONTRIBUTING.md).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by afuetterer** [comment]
Sure, you can get include PRs from the Dependabot as well.

#717
#719

There were several JS related ones, that you needed to close before the release, right?

**Comment by MyPyDavid** [comment]
yeah, there are over 10 JS PRs closed after the release. How should we handle these?
Merge them here and make a local test for review? Or is the npm build sufficient for that?

**Comment by afuetterer** [comment]
I think if a JS library has a patch version update like #719, it should be safe to just merge.

The npm run build check is a kind of brittle test, it checks if webpack can build a bundle with the defined dependencies. If the frontend then works is another question.

I think you could also try to run `npm audit` or `npm audit fix` to get multiple security related updates in one go.
https://docs.npmjs.com/cli/v6/commands/npm-audit

There are a few major version updates in https://github.com/rdmorganiser/rdmo/pulls?q=is%3Apr+is%3Aclosed+label%3Ajavascript

So short answer: I dont really know. :)

**Comment by afuetterer** [comment]
Maybe we wait for the frontend-tests to be completed for the other js dependency updates to be sure nothing broke?

We could merge this branch now and deal with the other dependabot PRs later. What do you think?

**Comment by MyPyDavid** [comment]
yes think so too.
Think that still some parts should be tested manually but can do that as part of the release at the end as well.

**Review by afuetterer — APPROVED** [review]

**Review by jochenklar — APPROVED** [review]

**Pull request merged**
