### PR TITLE
Add uri_path to factories

### PR DESCRIPTION
**Pull request by jochenklar**
I just had the idea that, if you create a question, the `uri_path` of the page is already in the form. This PR adds this. I am not sure, if we should add the `/` to the path already. If we don't just creating the element without editing will give a validation error (which is good I think), but then we always need to add the slash.

### CODE REVIEW

**Comment by Zack-83** [comment]
I have no strong opinion. Just for comparison: `uri_prefix` is defined without slash.

**Review by Zack-83 — APPROVED** [review]

**Comment by Zack-83** [comment]
> Clarification: The inserted `uri_path` is the path of the parent, e.g. page `catalog/section/page`. The idea is that I only need to add "question" to get `catalog/section/page/question` as `uri_path` for the question. If we insert `catalog/section/page/` people just need "question", but if they just hit save a question with `catalog/section/page/` will be saved (which the user does not want). If we insert `catalog/section/page` people need to type an addtional `/`, but when they just hit save, there will be a validation error since `catalog/section/page` is already the `uri_path` of the page.

This argument supports the `uri_path` without `/`.

**Review by MyPyDavid — CHANGES_REQUESTED** [review]
I think so too that the the path should be set without the `/`, so that the user has to type out the rest of the path before creation. 
Otherwise a simple click on create would make a wrong uri.

**Review by MyPyDavid — APPROVED** [review]
thanks, test only fails on this (twine, importlib_metadata) build step

**Pull request merged**
