### PR TITLE
Refactor help

### PR DESCRIPTION
**Pull request by jochenklar**
## Description

This PR:

* Adds a custom {more} markdown tag
* Adjusts the style for the details/summary html tags

Related issue: #595

### CODE REVIEW

**Comment by MyPyDavid** [comment]
how does one reproduce this with the `{more}` tag??

**Comment by jochenklar** [comment]
If you use `{mask}` in any help text, the show more tag should be visible.

**Comment by MyPyDavid** [comment]
thanks, found it!
And what about Uebersetzung?
```
Bitte beschreiben Sie kurz das Projekt und dessen Ziele. ... (show more)
```

**Comment by jochenklar** [comment]
Lets do the translations when we merged everything together.

**Review by MyPyDavid — APPROVED** [review]

**Pull request merged**
