### PR TITLE
Fix attribute serializer

### PR DESCRIPTION
**Pull request by jochenklar**

### CODE REVIEW

**Comment by jochenklar** [comment]
Fixes https://github.com/rdmorganiser/rdmo/issues/552

**Review by MyPyDavid — APPROVED** [review]
thanks, this fixes the issue!

**Comment by MyPyDavid** [comment]
this one is missing from the `1.9.1` release branch! @jochenklar 
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

It probably happened when the `dev` branch was behind the `master` branch...

**Comment by jochenklar** [comment]
Hmm, how did that happen? Well `1.9.2` it is, but maybe on monday ... @triole

**Pull request merged**
