### PR TITLE
Add JSONExport for projects and refactor CSVExport

### PR DESCRIPTION
**Pull request by jochenklar**

### CODE REVIEW

**Comment by jochenklar** [comment]
@triole @MyPyDavid @m6121 I am unsure if we should include the JSON export by default, and also if we should provide both CSV exports by default. Any ideas/feelings?

**Comment by m6121** [comment]
Hi @jochenklar,
maybe from an end user point of view the xml will be most interesting for backup and import of their projects. I have no idea how frequently the CSV and JSON are used. Maybe we could comment the CSV and JSON export and leave the XML active by default so that admins might easily activate if they wish.

**Comment by MyPyDavid** [comment]
there was a use for CSV, better leave both of them for ease of use..
what is the use case for JSON for normal users or site managers?
It could be added and left out of the template but then `PROJECT_EXPORTS` would need another feature flag, for example
```py
    ('csvsemicolon', _('CSV semicolon separated'), 'rdmo.projects.exports.CSVSemicolonExport' , True or False #show in template)
```

**Comment by jochenklar** [comment]
I think everybody can use the JSON export. It is the same data as the csv export.

**Comment by MyPyDavid** [comment]
need to change base branch to https://github.com/rdmorganiser/rdmo/tree/dev-2.0.0

**Comment by jochenklar** [comment]
I will merge and we can adjust the default export list later.

**Pull request merged**
